---
title: "Netcdf Data Processing"
output: html_notebook
---

This notebook process raw Netcdf codes from Randall Martin's surface PM2.5 exposure dataset(https://sites.wustl.edu/acag/datasets/surface-pm2-5/)

```{r}
library(ncdf4)
library(raster)
library(tidyverse)
library(geometry)
library(data.table)
library(maps)
library(magrittr)
library(ggplot2)
library(sf)
library(reshape2) # For reshaping data
library(mapdata)  # For map data
library(ggmap)

```


```{r}
nc_file <- nc_open("../data/input/pm25_components/PM25/V4NA03_PM25_NA_200001_200012-RH35.nc")
print(nc_file)

```
```{r}
pm25 <- ncvar_get(nc_file, "PM25")
lon <- ncvar_get(nc_file, "LON")
lat <- ncvar_get(nc_file, "LAT")
```

```{r}
# Reshape data
pm25_df <- melt(pm25)
pm25_df$lon <- rep(lon, each = length(lat))
pm25_df$lat <- rep(lat, length(lon))
pm25_df <- na.omit(pm25_df) # Remove NA values
# Remove the "Var1" and "Var2" columns from pm25_df
pm25_df <- pm25_df %>% select(-c(Var1, Var2))

```

```{r}
# Save pm25_df as Rdata to the specified path
saveRDS(pm25_df, file = "../data/output/pm25_df.Rdata")
```


```{r}
# Sample 100 rows from the data frame
pm25_sample <- pm25_df %>% sample_n(10000)

# Create plot for pm25 sample
ggplot(pm25_sample, aes(x = lon, y = lat, color = value)) +
  geom_point() +
  scale_size_continuous(range = c(1, 10), guide = "none") +
  scale_color_gradient(low = "blue", high = "red") +
  xlab("Longitude") +
  ylab("Latitude") +
  ggtitle("PM25")


```

```{r}
# Sample 100 rows from the data frame
pm25_sample_1 <- pm25_df %>% sample_n(1000)

# turn it into an sf object, for spatial plotting
pm25_sf <- pm25_sample_1 %>% 
  st_as_sf(coords = c('lon', 'lat')) %>%
  st_set_crs(4326) # using 4326 for lat/lon decimal 

# ggplot2 of the data
ggplot() +
  geom_sf(data = pm25_sf, aes(color = value), size = 1)

```



```{r}
# Getting a little fancier with it by adding the state borders
us_map <- rnaturalearth::ne_states(country = 'United States of America', returnclass = 'sf') %>%
  filter(!name %in% c("Hawaii", "Alaska"))

```


```{r}
ggplot() + 
  geom_sf(data = pm25_sf, aes(color = value), size = 0.5) + 
  geom_sf(data = us_map, fill = NA)
```


